uint16 absolute                # UMB Channel 300, 300 - 1200 [hPa]
bool absolute_valid
uint16 absolute_min            # UMB Channel 320, 300 - 1200 [hPa]
bool absolute_min_valid
uint16 absolute_max            # UMB Channel 340, 300 - 1200 [hPa]
bool absolute_max_valid
uint16 absolute_avg            # UMB Channel 360, 300 - 1200 [hPa]
bool absolute_avg_valid

uint16 relative                # UMB Channel 305, 300 - 1200 [hPa]
bool relative_valid
uint16 relative_min            # UMB Channel 325, 300 - 1200 [hPa]
bool relative_min_valid
uint16 relative_max            # UMB Channel 345, 300 - 1200 [hPa]
bool relative_max_valid
uint16 relative_avg            # UMB Channel 365, 300 - 1200 [hPa]
bool relative_avg_valid