float32 relative                # UMB Channel 200, 0.0 - 100.0 [%]
bool relative_valid
float32 relative_min            # UMB Channel 220, 0.0 - 100.0 [%]
bool relative_min_valid
float32 relative_max            # UMB Channel 240, 0.0 - 100.0 [%]
bool relative_max_valid
float32 relative_avg            # UMB Channel 260, 0.0 - 100.0 [%]
bool relative_avg_valid

float32 absolute                # UMB Channel 205, 0.0 - 1000.0 [g/m³]
bool absolute_valid
float32 absolute_min            # UMB Channel 225, 0.0 - 1000.0 [g/m³]
bool absolute_min_valid
float32 absolute_max            # UMB Channel 245, 0.0 - 1000.0 [g/m³]
bool absolute_max_valid
float32 absolute_avg            # UMB Channel 265, 0.0 - 1000.0 [g/m³]
bool absolute_avg_valid

float32 mixing_ratio            # UMB Channel 210, 0.0 - 1000.0 [g/kg]
bool mixing_ratio_valid
float32 mixing_ratio_min        # UMB Channel 230, 0.0 - 1000.0 [g/kg]
bool mixing_ratio_min_valid
float32 mixing_ratio_max        # UMB Channel 250, 0.0 - 1000.0 [g/kg]
bool mixing_ratio_max_valid
float32 mixing_ratio_avg        # UMB Channel 270, 0.0 - 1000.0 [g/kg]
bool mixing_ratio_avg_valid