float32 current         # UMB Channel 100, -50.0 - 60.0 [°C]
bool current_valid
float32 minimum         # UMB Channel 120, -50.0 - 60.0 [°C]
bool minimum_valid
float32 maximum         # UMB Channel 140, -50.0 - 60.0 [°C]
bool maximum_valid
float32 average         # UMB Channel 160, -50.0 - 60.0 [°C]
bool average_valid

float32 dewpoint         # UMB Channel 110, -50.0 - 60.0 [°C]
bool dewpoint_valid
float32 dewpoint_min     # UMB Channel 130, -50.0 - 60.0 [°C]
bool dewpoint_min_valid
float32 dewpoint_max     # UMB Channel 150, -50.0 - 60.0 [°C]
bool dewpoint_max_valid
float32 dewpoint_avg     # UMB Channel 170, -50.0 - 60.0 [°C]
bool dewpoint_avg_valid


float32 wind_chill       # UMB Channel 111, -60.0 - 70.0 [°C]
bool wind_chill_valid

float32 wet_bulb         # UMB Channel 114, -50.0 - 60.0 [°C]
bool wet_bulb_valid

float32 wind_heater      # UMB Channel 112, -50.0 - 150.0 [°C]
bool wind_heater_valid
float32 r2s_heater       # UMB Channel 113, -50.0 - 150.0 [°C]
bool r2s_heater_valid

