lufft_ws:
   ros__parameters:
      query_interval: 1.0                 # Defines the interval between two queries to the sensor in seconds. Messages will be published at the same interval.
      umb_channels: [                     # List of the UMB channels to querry. See: https://www.lufft.com/download/manual-lufft-wsxxx-weather-sensor-en/
         620, 625, 820, 825
      ]
      device: "/dev/rs485_adapter_0"      # The port where the sensor is connected
      baudrate: 19200                     # Baudrate of that port
      device_id: 1                        # The device ID of the sensor. Can be configured in the Lufft ConfigTool.NET.
